import Link from "next/link";

export const revalidate = 60 // revalidate at most every 5 minutes


const TermsOfUse = () => {
    return (
      <section className="course-overview md:px-0 px-10 max-w-[1000px] mx-auto">
         
           <div className="container ">
           <h1 className="font-extrabold py-10 text-5xl text-[#000000] leading-tight">Terms of Use</h1>
        <div className="et_pb_module et_pb_text et_pb_text_1  et_pb_text_align_left et_pb_bg_layout_light">
				
				
				
				
				<div className="et_pb_text_inner leading-[33px] space-y-6">
                    <h4 className="text-[18px] text-[#000000] font-bold"  >1. USE OF THE SITE</h4>
<p className="text-[18px] text-[#000000]" >PLEASE CAREFULLY REVIEW THE TERMS OF USE OF THIS SITE AND THE TERMS OF<span></span><Link href="/privacy-statement/">OUR PRIVACY STATEMENT</Link><span></span>BEFORE USING THIS SITE OR ANY OF OUR SITES, OR ANY GOODS OR SERVICES FROMOUR SITE.</p>
<p className="text-[18px] text-[#000000]" >By using this Site, including downloading or accessing Materials, ordering products or otherwise using the Services, you agree to be bound by, and acknowledge your acceptance of these Terms of Use.From time to time, we may update these Terms of Use.We encourage you to periodically review these terms for any material changes.You agree to be bound by all of the provisions of these Terms of Use that are displayed on the SITE on the date you use the Site and/or any part of the Service.Your use of the Site, and/or any part of the Service, indicates your acceptance of all of the provisions of these Terms of Use that are displayed on the Site on the date of such use.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >2. DESCRIPTION OF SITE AND THE SERVICE.</h4>
<p className="text-[18px] text-[#000000]" >We may provide, through the Site, Services that include without limitation the:</p>
<p className="text-[18px] text-[#000000]" >(a) provision of the Site and other online services and Internet sites;</p>
<p className="text-[18px] text-[#000000]" >(b) display, performance, provision, and use of: information such as educational, promotional, product, pricing, marketing or other valuable information (“Information”); copyrighted works, photographs, text, music, video, sound, graphics, messages, and other Materials, including Our Materials and Third Party Materials (“Content”); and our and Third Parties’ Trademarks;</p>
<p className="text-[18px] text-[#000000]" >(c) interactive communication through chat, message boards, VOIP and other media, and</p>
<p className="text-[18px] text-[#000000]" >(d) offering of products and services for sale, license, distribution or use.</p>
<p className="text-[18px] text-[#000000]" >You can contact us about this Site or about accessing and changing any personal information you provide at this Site through contact information contained on the Site.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >3. OWNERSHIP OF INTELLECTUAL PROPERTY OF THIS SITE AND MATERIALS.</h4>
<p className="text-[18px] text-[#000000]" ><strong>3.1. Trademarks, Copyright and Intellectual Property Ownership.</strong></p>
<p className="text-[18px] text-[#000000]" >We use names, marks, brands, design marks, slogans, logos, designs, trade dress and trade names on the Site or with the Service “Our Trademarks”. We own all Trademarks, the Content, and other information displayed and posted on, contained in, and/or provided in connection with, the Site and/or the Service (collectively, “Our Materials). Also, third parties have allowed us to post or use their materials and Trademarks on Site (“Third Party Materials”); all blog entries are considered Third Party Materials.We refer to Our Materials and Third Party Materials collectively as the “Materials”.</p>
<p className="text-[18px] text-[#000000]" ><strong>3.2 Copyright Notice.</strong></p>
<p className="text-[18px] text-[#000000]" >Our Materials contained on the Site are copyrighted materials of Campus Crusade for Christ, Inc.</p>
<p className="text-[18px] text-[#000000]" >Copyright © 1993-2007 Campus Crusade for Christ, Inc. All rights reserved. International copyright secured.</p>
<p className="text-[18px] text-[#000000]" >We exclusively own, or have the right to use or license, all intellectual property in the Materials, proprietary information and know-how used with the Site and Services. We maintain all of the web pages of the Site as a collective work under the U.S. copyright laws and protect the Site and Materials under others’ trademark and other intellectual property laws.</p>
<p className="text-[18px] text-[#000000]" ><strong>3.3 Rights in Materials.</strong></p>
<p className="text-[18px] text-[#000000]" >By using or accessing the Site or services, you do not acquire any rights or interest in any Materials. The only rights you can gain are those we explicitly grant to you through these Terns of use. We reserve all rights that we do not expressly grant to you.</p>
<p className="text-[18px] text-[#000000]" >You agree not to display, use (including co-branding your owns goods or services with our Trademark), remove, or alter our or Third Party Trademarks, Content or other Information without prior written consent.</p>
<p className="text-[18px] text-[#000000]" >You also agree that any use by you, or on your behalf, of our Trademarks, and the goodwill associated therewith, shall insure to our benefit.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >4.RESTRICTIONS ON USE OF CONTENT, MATERIALS AND MARKS.</h4>
<p className="text-[18px] text-[#000000]" >Your use of the Site is strictly and exclusively limited to personal, non-commercial use.Your use is also subject to Our and Third Party Intellectual Property Rights. Except as expressly authorized in these Terms of Use, you agree that:</p>
<ul className="text-[18px] text-[#000000]">
<li>You will not reproduce, edit, modify, rent, license, sell, distribute, mirror, republish, download, transmit, or create derivative works from any Materials displayed on, or made available through the Site, or in connection with the Service, in whole or in part, by any means now known or later developed;</li>
<li>You will not modify, decompile, or reverse engineer any part of the Software;</li>
<li>You will not copy, post or transmit any Materials that you receive from, access, or retrieve from, the Site or through the Service, to any server, or network of computers;</li>
<li>You will not remove or modify any copyright or trademark notice, or other notice of ownership, displayed on, or affixed to, any Materials, including any copies of the Licensed Materials that you download and/or distribute; and</li>
<li>You will not frame the Site within a mark other than that of Our Ministry.</li>
</ul>
<p className="text-[18px] text-[#000000]" ><strong>4.1 Proper notice required</strong></p>
<p className="text-[18px] text-[#000000]" >Any authorized uses of Our Materials, including any authorized reproduction, transmission, broadcast or adaptations permitted under these Terms of Use, must contain the following Copyright notice:</p>
<p className="text-[18px] text-[#000000]" >“Copyright © 2020 Cities Project Global. All rights reserved. Used by permission.”</p>
<p className="text-[18px] text-[#000000]" >All other copyright notices and Trademark notices should be maintained and displayed, as displayed on the Site or on the relevant Work, or as otherwise instructed by Us.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >5.LIMITED LICENSE FOR DOWNLOADABLE MATERIALS.</h4>
<p className="text-[18px] text-[#000000]" ><strong>5.1 Downloadable Materials.</strong></p>
<p className="text-[18px] text-[#000000]" >We may identify certain materials on our Site as being downloadable (“Licensed Materials”). You may download one copy of these identified downloadable materials subject to the restrictions of the Terms.We grant to you a limited, non-exclusive, non-transferable, non-sublicensable, license to view, print, and make one copy of the Licensed Materials for only informational, educational, non-commercial, personal purposes and without alteration of the materials (the “License”). You can use the Licensed Materials only in the format in which we make them available on the Site for download, and only in authorized distributions.</p>
<p className="text-[18px] text-[#000000]" >The License is subject to the following additional restrictions:</p>
<p className="text-[18px] text-[#000000]" >(a) You cannot charge or collect any Distribution Fee for the distribution of any of the Licensed Materials;</p>
<p className="text-[18px] text-[#000000]" >(b) All copyright, trademark or other proprietary notices that appear on the Licensed Materials, together with the permission notice, must appear on all copies of the Licensed Materials that you make or distribute;</p>
<p className="text-[18px] text-[#000000]" >(c) You shall not use, copy or distribute any graphics comprising part of the Licensed Materials separate from accompanying text;</p>
<p className="text-[18px] text-[#000000]" >(d) You shall not use the Licensed Materials in connection with, or relation to, any fundraising activities;</p>
<p className="text-[18px] text-[#000000]" >(e) You shall not use the Licensed Materials in a manner that suggests an association with or endorsement by US, or any of our products, services, or brands; and</p>
<p className="text-[18px] text-[#000000]" >(f) You shall not download quantities of Licensed Materials to a database that can be used to avoid future downloads of any of the Licensed Materials from any of the Sites.</p>
<p className="text-[18px] text-[#000000]" ><strong>Distribution Fee.</strong>The term “Distribution Fee” means any and all payments of monies, fees, royalties, remuneration, donations, gifts or other consideration, whether in cash or like-kind, received by, paid to, owed to, on or behalf of, a user or a distributor that arise from, or are in any way related to the provision, transmission, distribution, sale, license, lease, rental or other use of the Licensed Materials, including specifically without limitation, any fundraising activities.</p>
<p className="text-[18px] text-[#000000]" ><strong>5.2 Download of General Content.</strong><br /> For the materials not clearly identified and intended as downloadable materials (“General Content”) we grant you a limited, non-exclusive license to print one copy of the General Content, without alteration for your use for informational, non-commercial, private or personal purposes only. No other use of downloaded General Content is allowed unless specifically allowed on the Site. You shall not copy any of the General Content or Materials or Content on our websites, onto another website. You may, however, access the Materials or Contents of our websites through a hyperlink.</p>
<p className="text-[18px] text-[#000000]" ><strong>5.3 Reservation of Rights.</strong>We reserve any rights not expressly granted herein.</p>
<p className="text-[18px] text-[#000000]" ><strong>5.4 Termination of License.</strong>We may terminate the License and any of the rights at any time by providing notice of<br /> termination on the Site or directly to you as a user. Further, the License shall automatically terminate without notice if you breach any of the terms or conditions of the License or these Terms of Use. Upon termination of the License, you agree to immediately destroy, and cease all use or distribution of, any downloaded, printed or electronically stored copies of the Licensed Materials or General Content.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >6.PERSONAL INFORMATION AND PRIVACY OF INFORMATION</h4>
<p className="text-[18px] text-[#000000]" ><strong>6.1. Provision of Your Personal Information.</strong></p>
<p className="text-[18px] text-[#000000]" >As a user of the Site, you can visit certain areas of the Site without revealing any information about yourself. In other parts of Our Site, you may be required to provide information for certain purposes, including registering for a service, completing a transaction, making a donation, sending correspondence, purchasing or ordering a product or gaining access to a portion of the Site or a Service. Any information you provide to the Site is referred to as “Registration Data”.</p>
<p className="text-[18px] text-[#000000]" >We encourage you not to use, submit or provide any personal or sensitive information beyond what is requested or required for your transactions with us or our ministry affiliates. We shall have no responsibility for use, misuse, loss or alteration of any information (including Registration Data) provided by you. This includes any information, content, materials or ideas that you provide without our request.</p>
<p className="text-[18px] text-[#000000]" ><strong>6.2 Accuracy of Personal Information.</strong></p>
<p className="text-[18px] text-[#000000]" >In operating our Site we seek to provide valuable information and we value accurate and honest communication. In using the Site, you agree to provide true, accurate, current and complete information about yourself in Registration Data or other data and materials you provide. It is your responsibility to maintain the security of all passwords, user identification data, and other unique identifiers established in connection with your use of any part of the Site and/or the Service, including any Forum (defined below). As part of your use, you agree to maintain and promptly update the Registration Data, and any other information you provide and to keep it true, accurate, current and complete.</p>
<p className="text-[18px] text-[#000000]" >If you provide any information that is untrue, inaccurate, not current or incomplete, or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, we have the right to suspend or terminate your access to the Site, and to refuse any and all current or future access to, or use of, the Site and the Service.</p>
<p className="text-[18px] text-[#000000]" ><strong>6.3 Privacy.</strong></p>
<p className="text-[18px] text-[#000000]" >Any Registration Data and certain other information about you that we obtain from you through use of the Site is subject to our Privacy Statement. For more information,<span></span><Link href="/privacy-statement/">see our full Privacy Statement</Link>.</p>
<p className="text-[18px] text-[#000000]" ><strong>6.3 Use by Minors.</strong></p>
<p className="text-[18px] text-[#000000]" >We are concerned about the safety and privacy of all of our Site’s users, particularly children. This Site is not directed or targeted to children. We ask that parents supervise their children while visiting the Site as with any Site on the Internet. For this reason, parents who wish to allow their children under the age of 13 to provide personal information to our Site must provide permission through sending an e-mail to the contact information listed on the Site prior to any submission of personal information by such child.</p>
<p className="text-[18px] text-[#000000]" >A parent of any minor providing information to our Site can:</p>
<p className="text-[18px] text-[#000000]" >(a) ask to review any personal information about his/her child that we may have collected at the Site;</p>
<p className="text-[18px] text-[#000000]" >(b) request that we delete this information (if we still have the information in our databases); and/or</p>
<p className="text-[18px] text-[#000000]" >(c) instruct us not to collect or use his/her child’s information in the future.</p>
<p className="text-[18px] text-[#000000]" >If you are a parent and wish to exercise this right, simply contact us at the contact information listed on the site. For more information, please refer to our Privacy Statement. In the absence of parental permission, you certify by using the Site or any part of the Service, that you are at least 13 years of age. If you are ordering or purchasing any product, you agree that you are 18 years of age, or at least the age of majority for purposes of entering into an enforceable contract in the jurisdiction in which you reside.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >7.GENERAL USE RULES.</h4>
<p className="text-[18px] text-[#000000]" >To facilitate everyone’s enjoyment of the Site, we have set out our General Use Rules for you here. Generally speaking, these rules simply require respect and good manners. Use common sense and you will feel right at home.</p>
<p className="text-[18px] text-[#000000]" ><strong>No Obscenity.</strong>We do not allow obscene, racist, vulgar, discourteous, indecent or sexually explicit language or images. You agree not to post, upload, e-mail, transmit, distribute, or otherwise make available, any such content or materials onto any of the Site, including any Forum.</p>
<p className="text-[18px] text-[#000000]" ><strong>No Posting or Communication of Infringing Material or Harassing Communications or Advertisements.</strong>You also agree not to post, communicate, upload, e-mail, transmit, distribute, or otherwise make available:</p>
<ul className="text-[18px] text-[#000000]">
<li>any material or content that infringes and/or violates any right of a third party (including its intellectual property and proprietary rights), or any law;</li>
<li>any harassing, slanderous, libelous or derogatory information or content, or</li>
<li>any advertisements for products or services, “junk mail”, spam, chain mail, pyramid schemes, or other form of commercial or illegal solicitation;</li>
</ul>
<p className="text-[18px] text-[#000000]" ><strong>No Commercial Uses.</strong>You agree not to use the Forum or the Site for commercial purposes of any kind;</p>
<p className="text-[18px] text-[#000000]" ><strong>No Harm to Minors.</strong>You agree not to harm, or attempt to harm, lure or deceive minors in any way;</p>
<p className="text-[18px] text-[#000000]" ><strong>No False Identity</strong>. You agree not to create or use a false identity for the purpose of misleading others;</p>
<p className="text-[18px] text-[#000000]" ><strong>Do Not Collect or Store Personal Data.</strong>You agree not to collect or store personal data about other users;</p>
<p className="text-[18px] text-[#000000]" ><strong>No Virus or Disabling Software.</strong>You agree not to post or distribute any software or other materials that contain a virus, worm, trojan horse or other harmful or disabling code or component;</p>
<p className="text-[18px] text-[#000000]" ><strong>No Interference with the Site or Service.</strong>You agree not to interfere with, or disrupt, the operation of the Site and/or the Service, or with servers or networks connected to, or used in connection with the operation of the Site.</p>
<p className="text-[18px] text-[#000000]" ><strong>Obey Requirements.</strong>You agree not to disobey any requirements, procedures, policies or regulations established by the owners or operators of any networks, hardware, or software connected to, or used in connection with the operation of the Site, or any requirement that we post on theSite.</p>
<p className="text-[18px] text-[#000000]" ><strong>Respect Privacy of Others.</strong>You must respect the privacy of others. You agree not to post or disclose phone numbers, addresses, Social Security numbers, or any other private information, relating to any other person.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >8.FORUM, CHAT AND INTERACTIVE PARTICIPATION AND USER POSTED INFORMATION AND CONTENT.</h4>
<p className="text-[18px] text-[#000000]" ><strong>8.1 Truthful Participation and Assumption of Risk in Interactive Communications.</strong></p>
<p className="text-[18px] text-[#000000]" >Through our Site, you may participate in a number of interactive communication activities including chat, Forums, message boards, email, VOIP and other means of interactive communication with other participants (“Interactive Communications”). We cannot be, and we are not, responsible for the content, opinions or accuracy of any information provided or posted in any Interactive Communication. You participate at your own risk when engaging in any activity relating to the Site and/or the Service (including any Interactive Communication). You expressly assume all risk and take full and sole responsibility for (a) all postings using, or made under, your Passwords or Your Accounts; (b) and any use of any Information, Content or Materials provided or displayed on, or contained in, the Site (including in any Forum) and (c) any communication or interaction with other users through the Site. When participating in a Forum or Interactive Communication, you are wise to never assume that people are who they say they are, know what they say they know, or are affiliated with who they say they are. The term “Forum” means a chat area, message board, e-mail or other function that allows you to provide information or interact with others offered as part of Our Site. Portions of Our Site may allow users to post their own material. The materials posted by users do not necessarily reflect our views and we shall not be liable for any user information posted or displayed on, or uploaded onto any of the Site, including any Forum.</p>
<p className="text-[18px] text-[#000000]" ><strong>8.2 Posting Materials to Site.</strong></p>
<p className="text-[18px] text-[#000000]" >By posting materials to or communicating with other participants on the Site or in an Interactive Communication, you represent and warrant to us that: (a) you have all necessary rights to such materials, and that the posting of such materials will not infringe on any personal or proprietary rights of any third party, including its intellectual property rights; and (b) such materials are not harmful, defamatory, unlawful, threatening, obscene, lewd, lascivious, harassing, and/or contrary to the principles, tenets, and Mission Statement of Our Organization.</p>
<p className="text-[18px] text-[#000000]" ><strong>8.3 We have the Right to Remove or Block Postings or Interactive Communications.</strong></p>
<p className="text-[18px] text-[#000000]" >We reserve the right to remove or block any and all postings and Interactive Communications, including those that we consider to be:</p>
<ul className="text-[18px] text-[#000000]">
<li>Defamatory, libelous, slanderous or disparaging of, or insulting to, any person, group or entity; abusive or hateful; obscene, lewd, or vulgar; or contrary to, or inconsistent with, the principles, tenets, and Mission Statement of Our Organization,</li>
<li>Any harassing notes, postings or Interactive Communications that might be construed as stalking, or any postings that might otherwise be illegal or relate to illegal activity, any such harassing content or communications will be deleted and may be made available to the proper law-enforcement officials. While we reserve the right to remove any posting, we shall have no obligation to do so.</li>
</ul>
<h4 className="text-[18px] text-[#000000] font-bold" >8.4 Ownership in Posted Material.</h4>
<p className="text-[18px] text-[#000000]" >By uploading or communicating any materials, ideas or submissions to any of our Site, including any Forum, or submitting any materials to us in any other manner, you automatically grant (or warrant that the owner of such materials expressly granted) to us a perpetual, royalty-free, irrevocable, nonexclusive right and license to use, reproduce, modify, adapt, publish, translate, publicly perform and display, create derivative works from and distribute such materials, or to incorporate such materials into any form, medium, or technology now known or later developed. In addition, you waive and warrant that all so-called “moral rights” in those materials have been waived. You agree that we own any derivative works, improvements or other materials, works, ideas, intellectual property, and/or products created from, based on, or related to, our access to, or use of, any materials you provide. If on a particular Site we have included an upload license, those terms should be noted as also applying, with any conflicts governed by these Terms of Use.</p>
<p className="text-[18px] text-[#000000]" ><strong>8.5 Disclaimer on Information Received from Volunteers.</strong></p>
<p className="text-[18px] text-[#000000]" >Our Organization provides general information regarding spiritual matters and religious questions through the Internet and Ministry Response Center Volunteers. We make this information available solely for informational and educational purposes. Please be aware that the information is not prepared by licensed counselors, medical or mental health professionals and it is not provided as medical, mental, or other professional advice. You should not use or rely on any information or advice provided by Our Ministry or any Volunteer in lieu of medical, mental health, physical or other professional assistance or counseling. Instead, you should always consult with your physician, psychologist, psychiatrist, pastor, rabbi, priest, cleric or other spiritual advisor.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >9.ACTIVITIES WITH THIRD PARTIES ON OR FROM THE SITE</h4>
<p className="text-[18px] text-[#000000]" ><strong>9.1 Linking to Third Party Sites from Our Site.</strong></p>
<p className="text-[18px] text-[#000000]" >From time to time, we may provide links on the Site that will allow you to connect with web sites of third-parties that are not under our control. We are providing these links only as a convenience to you. Further, there may be times while in the Site that you could be directed to sites that are beyond our control. This includes links from other organizations, sponsors or volunteers that may use our logo(s) as part of an agreement with us. These other sites may send their own cookies to users, collect data, solicit personal information, or contain information that you may find inappropriate or offensive.</p>
<p className="text-[18px] text-[#000000]" ><strong>9.2 No Warranties.</strong></p>
<p className="text-[18px] text-[#000000]" >WE MAKE NO REPRESENTATIONS OR WARRANTIES CONCERNING THE CONTENT OF, OR THE PRIVACY PRACTICES OF, OR THE AVAILABILITY OR QUALITY OF ANY PRODUCTS, MATERIALS OR SERVICES THAT YOU PURCHASE FROM A THIRD-PARTY WEBSITE THAT LINKS TO OR FROM ANY OF OUR SITES EVEN IF WE PROVIDE LINKS TO SUCH SITES ON THE SITE. WE ACCEPT NO RESPONSIBILITY FOR, AND WE EXPRESSLY DISCLAIM ANY WARRANTIES OR LIABILITY RELATING TO, THE ACCURACY, RELEVANCY, COPYRIGHT COMPLIANCE, LEGALITY, OR DECENCY OF MATERIALS DISPLAYED ON, OR CONTAINED IN, WEB SITES LINKED TO, OR TO WHICH YOU ARE DIRECTED FROM, ANY OF THE SITES. YOU ACCESS AND USE SUCH WEB SITES, AND THE SERVICES PROVIDED IN CONNECTION THEREWITH, AT YOUR OWN RISK. WE ENCOURAGE YOU TO REVIEW THE TERMS OF USE AND PRIVACY STATEMENTS POSTED ON ANY THIRD PARTY WEB SITE, OR TO CONTACT THE OPERATOR OF THE WEB THE SITE PRIOR TO USING, OR PROVIDING ANY INFORMATION ON, SUCH THIRD PARTY WEB SITES.</p>
<p className="text-[18px] text-[#000000]" ><strong>9.3. No Endorsement.</strong></p>
<p className="text-[18px] text-[#000000]" >Links to other web sites do not imply an endorsement of the materials, products, content, ideas or Interactive Communications displayed on, or disseminated at or through those web sites, nor does the existence of a link to another of our Sites imply that the organization or person publishing at that Site endorses any of the materials or ideas at our Site. We reserve the right to disable links from third-party sites to any of our Sites at any time without prior notice.</p>
<p className="text-[18px] text-[#000000]" ><strong>9.4 Rules for Linking to Our Site.</strong></p>
<p className="text-[18px] text-[#000000]" >We may provide the option for you to post a link to our site from your website or other third party sites. We reserve the right to, at any time and without prior notice, ask you to remove the link should we determine it to have a negative effect on our website, search engine results or other negative impact on our visitors. You agree to remove the link immediately upon request.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >10.PRODUCT SALES, DONATIONS, SUBSCRIPTIONS AND FEES</h4>
<p className="text-[18px] text-[#000000]" ><strong>10.1 Product Sales and Availability.</strong></p>
<p className="text-[18px] text-[#000000]" >We may sell certain products and materials on our Sites. All prices for products and materials sold through the Site are quoted in U.S. Dollars, and are valid and effective only in the United States at the time of posting. If we provide products or materials for delivery to certain locations outside the United States, we reserve the right to charge a higher price, or additional fees, for such products. We reserve the right to, at any time, and without prior notice, discontinue or change information, availability and pricing on any product or Materials on our Site, without incurring any obligations to you or any other party. You are responsible for any applicable use taxes of your jurisdiction imposed as user or buyer of products or services.</p>
<p className="text-[18px] text-[#000000]" ><strong>10.2.Third Party Sales.</strong></p>
<p className="text-[18px] text-[#000000]" >WE MAKE NO REPRESENTATIONS WITH RESPECT TO THE AVAILABILITY OR QUALITY OF ANY PRODUCTS, MATERIALS OR SERVICES THAT YOU PURCHASE FROM A THIRD-PARTY WEBSITE THAT LINKS TO OR FROM ANY OF THE SITES, OR AS A RESULT OF THIRD-PARTY CONTENT (INCLUDING ADVERTISEMENTS OR SPONSORSHIPS) POSTED, DISPLAYED OR INCLUDED ON ANY OF THE SITES. WE DO NOT ENDORSE ANY OF THE PRODUCTS, NOR HAVE WE TAKEN ANY STEPS TO CONFIRM THE ACCURACY OR RELIABILITY OF ANY INFORMATION CONTAINED IN SUCH THIRD-PARTY SITES OR CONTENT (INCLUDING ADVERTISEMENTS).<br /> YOU HEREBY IRREVOCABLY AND FOREVER RELEASE AND WAIVE (ON BEHALF OF YOURSELF AND YOUR HEIRS, PERSONAL REPRESENTATIVE, AND PERMITTED ASSIGNS) ANY CLAIM AGAINST US RELATING TO, OR ARISING OUT OF, (A) THE OPERATION OR DISPLAY OF ANY THIRD-PARTY WEB-SITES AND THIRD-PARTY CONTENT, WHETHER OR NOT SUCH WEB SITES AND CONTENT ARE ACCESSIBLE THROUGH, OR DISPLAYED ON, THE SITE; (B) YOUR ACCESS OR USE OF ANY THIRD-PARTY WEB SITE OR THIRD-PARTY CONTENT; AND (C) ANY AND ALL PRODUCTS OR MATERIALS THAT YOU PURCHASE FROM ANY THIRD-PARTY WEB SITE, EVEN IF SUCH PRODUCT IS ADVERTISED ON THE SITE.</p>
<p className="text-[18px] text-[#000000]" >WE STRONGLY ENCOURAGE YOU TO MAKE WHATEVER INVESTIGATION YOU FEEL NECESSARY OR APPROPRIATE BEFORE PROCEEDING WITH ANY ON-LINE OR OFF-LINE TRANSACTION WITH THE OPERATOR OR OWNER OF A THIRD-PARTY WEB SITE OR THE PUBLISHER OR OWNER OF ANY THIRD-PARTY CONTENT DISPLAYED ON THE SITE.</p>
<p className="text-[18px] text-[#000000]" ><strong>10.3 Ownership of Third Party Materials</strong></p>
<p className="text-[18px] text-[#000000]" >Third Party Materials are owned, or licensed by the owner thereof, and, where necessary, we use such Third Party Materials with the permission of the owner. Unless we expressly indicate in these Terms of Use, you have no rights or interest in any Third Party Materials. All rights relating to these materials are reserved to their owner.</p>
<p className="text-[18px] text-[#000000]" ><strong>10.4 Donations.</strong></p>
<p className="text-[18px] text-[#000000]" >Donations made through our Site are verified, secure and confidential. Like any tax-deductible charitable contribution, any electronic giving made through our Site by credit card or electronic transfer is considered made and irrevocable at the time the contribution is submitted on our Site. For further information on the donor-advised fund labeled Cities Project Global Giving Fund or questions concerning donations you may contact National Christian Foundation at:<Link href="tel:1-800-681-6223">800.681.6223</Link>or visit our Web site at: <Link href="https://www.ncfgiving.com/">https://www.ncfgiving.com/</Link>.</p>
<p className="text-[18px] text-[#000000]" ><strong>10.5 Credit Cards.</strong></p>
<p className="text-[18px] text-[#000000]" >We take the issue of your privacy seriously. All credit card information submitted is protected by SSL (Secure Sockets Layer) encryption or similar technology. We provide your credit card number, billing and shipping information to participating merchants from whom you buy goods or services. These merchants are solely responsible for how they use that information and any other information they independently acquire from you or about you. Otherwise, we do not share or use your credit card information, except as described in our Privacy Statement, which we encourage you to read each time you visit any of our Sites.</p>
<p className="text-[18px] text-[#000000]" ><strong>10.6 Subscriptions, Fees and Billing.</strong></p>
<p className="text-[18px] text-[#000000]" >Some services offered on certain of Our Sites may require a subscription or other fee to receive Services (“Subscribed Services”). If you open an account for Subscribed Services on any of our Sites, you hereby agree to pay all charges to such account, including applicable taxes, in accordance with billing terms in effect at the time the fee or charge becomes payable and following all rules of the subscriptions. We reserve the right to change the amount of, or basis for determining, any fees or charges for services we provide, and to institute new fees, charges, or terms effective upon notice to you at the e-mail address you provide when establishing your account. We reserve the right to terminate your account(s) at any time for any reason.</p>
<p className="text-[18px] text-[#000000]" >10.6. 1. Each of our Sites with Subscribed Services will contain rules for payment, use and termination of the Subscribed Services. You agree to adhere to all such rules in using the Subscribed Services.</p>
<p className="text-[18px] text-[#000000]" >10.6. 2. Renewal: Your subscription for each Subscribed Service will be automatically renewed and your credit card account will be charged on the same time and cost basis as the prior subscription period unless a Site indicates otherwise.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >11.DISCLAIMERS.</h4>
<p className="text-[18px] text-[#000000]" >11.1. EXCEPT FOR THE LIMITED WARRANTIES OTHERWISE EXPRESSLY STATED AND DISPLAYED ON THE SITE RELATING TO CERTAIN PRODUCTS THAT WE SELL THROUGH THE INTERNET STORE, YOUR USE OF THE SITE, THE SERVICE, ALL CONTENT, ALL INFORMATION, AND ALL MATERIALS ARE OFFERED ON AN “AS IS” BASIS, “WITH ALL FAULTS,” AND “AS AVAILABLE,” WITHOUT ANY WARRANTIES WHATSOEVER, EITHER EXPRESS OR IMPLIED, TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW. WE EXPRESSLY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, RELATING TO THE SITE, ALL INFORMATION, CONTENT, MATERIALS, THE SOFTWARE, AND THE SERVICE, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS. WE DO NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE SITE AND/OR THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE; THAT DEFECTS OR ERRORS WILL BE CORRECTED PROMPTLY OR AT ALL; AND/OR THAT ANY OF THE SITE, INFORMATION, CONTENT, MATERIALS, THE SERVICE (AND/OR ANY SOFTWARE, SERVER, COMPUTER, HARDWARE, OR NETWORK RELATING TO THE OPERATION, OR HOSTING OF, ANY OF THE FOREGOING) WILL BE FREE OF VIRUSES, ERRORS, OR HARMFUL COMPONENTS. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. WE ASSUME NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY OR FAILURE TO STORE ANY COMMUNICATIONS OR MATERIALS POSTED ON OUR THE SITE OR IN ANY FORUM.</p>
<p className="text-[18px] text-[#000000]" >11.2. WE EXPRESSLY DISCLAIM ANY WARRANTIES, REPRESENTATIONS, OR RESPONSIBILITY FOR THE ACCURACY OR COMPLETENESS OF ANY INFORMATION, CONTENT, AND MATERIALS CONTAINED, DISPLAYED, OR POSTED ON THE SITE OR OTHERWISE AVAILABLE THROUGH OUR SITE, OR ON SITES THAT LINK TO OR FROM THE SITE. ALL SUCH INFORMATION, CONTENT AND MATERIALS ARE SUBJECT TO CHANGE WITHOUT NOTICE. WE DO NOT WARRANT, OR MAKE ANY REPRESENTATIONS WITH RESPECT TO, THE USE, OR THE RESULTS THAT MAY BE ACHIEVED THROUGH SUCH USE, OF ANY OF the SITEs, ANY PART OF THE SERVICE, AND/OR ANY INFORMATION, CONTENT, AND/OR MATERIALS.</p>
<p className="text-[18px] text-[#000000]" >11.3. AT ANY TIME AND WITHOUT NOTICE, WE MAY, FOR ANY REASON WHATSOEVER AND WITHOUT INCURRING ANY LIABILITY OR OBLIGATION TO YOU OR ANY OTHER PARTY, TERMINATE OR SUSPEND THE DISPLAY, OPERATION AND/OR PROVISION OF (A) THE-SITE (OR ANY PART THEREOF, INCLUDING ANY CONTENT, INFORMATION, AND/OR MATERIALS); (B) ANY PART OF THE SERVICE; AND/OR (C) YOUR ACCESS TO THE SITE OR ANY PART OF THE SERVICE.</p>
<p className="text-[18px] text-[#000000]" >11.4 WHILE WE WILL MAKE REASONABLE EFFORTS TO PROVIDE ACCURATE AND TIMELY INFORMATION, REPORTS AND PRAYER REQUESTS ON OUR SITE, YOU SHOULD NOT ASSUME THAT THE INFORMATION PROVIDED IS ALWAYS UP TO DATE, ACCURATE, COMPLETE OR THAT OUR SITE CONTAINS ALL OF THE RELEVANT INFORMATION AVAILABLE. IN PARTICULAR, IF YOU ARE MAKING A CONTRIBUTION DECISION REGARDING ANY OF OUR MINISTRIES, PLEASE CONSULT A NUMBER OF DIFFERENT AND INDEPENDENT SOURCES, INCLUDING THE CHARTER MEMBERSHIP INFORMATION AT THE EVANGELICAL COUNCIL FOR FINANCIAL ACCOUNTABILITY (ECFA).</p>
<h4 className="text-[18px] text-[#000000] font-bold" >12.LIMITATION OF LIABILITY.</h4>
<p className="text-[18px] text-[#000000]" >IN NO EVENT AND UNDER NO CIRCUMSTANCES SHALL WE BE LIABLE FOR ANY DAMAGES, INCLUDING WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES THAT RESULT FROM YOUR USE OF, OR INABILITY TO USE, ANY OF OUR SITE, ANY INFORMATION, ANY CONTENT, ANY MATERIALS, AND/OR THE SERVICE, OR ANY PART THEREOF, EVEN IF WE HAVE BEEN EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES. SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FO ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER IN CONTRACT, TORT, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, OR OTHERWISE) EXCEED THE AMOUNT PAID BY YOU TO US, IF ANY, FOR ACCESSING OR USING ANY OF THE SITE AND/OR FOR USING THE SERVICE OR ANY PART THEREOF. IF YOU ARE DISSATISFIED WITH ANY ASPECT OF THE SITE AND/OR SERVICE, IF YOU DO NOT AGREE WITH ANY PROVISION OF THESE TERMS OF USE, OR IF YOU HAVE ANY OTHER DISPUTE OR CLAIM, WITH OR AGAINST OUT ORGANIZATION WITH RESPECT TO THESE TERMS OF USE OF ANY OF THE SITE OR ANY PART OF THE SERVICE, THEN YOU ACKNOWLEDGE AND AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND/OR USING THE SITE AND/OR THE SERVICE.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >13.INDEMNITY.</h4>
<p className="text-[18px] text-[#000000]" >You are entirely responsible for maintaining the confidentiality of all Passwords and all accounts that you establish in conjunction with your use of Ours Sites or the Service (“Your Accounts”). You are solely responsible for all activities that occur under, or relating to, your Passwords and Your Accounts, and for your use of any of our Site and any part of the Service.</p>
<p className="text-[18px] text-[#000000]" >You hereby agree to indemnify, defend, and hold us, and our affiliates, our officers, directors, owners, agents, information providers, affiliates, licensors, and licensees (collectively, the “Indemnified Parties”), harmless from and against any and all liabilities and costs (including reasonable attorney’s fees) incurred by the Indemnified Parties in connection with any claim arising out of, or relating to:</p>
<p className="text-[18px] text-[#000000]" >(a) any breach by you of these Terms of Use;</p>
<p className="text-[18px] text-[#000000]" >(b) any unauthorized use by you of any Information, Content, Materials, our Site, or any part of the Service;</p>
<p className="text-[18px] text-[#000000]" >(c) your use of our Site and/or any part of the Service; and</p>
<p className="text-[18px] text-[#000000]" >(d) all activities relating to, or conducted under, your Passwords and/or Your Accounts.</p>
<p className="text-[18px] text-[#000000]" >You shall use your best efforts to cooperate with us in the defense of any such claim. We reserve the right, at our own expense, to assume the exclusive defense and control of any claim against you or use that is subject to indemnification by you. You agree that that in the event of any unauthorized use of our Site, any Information, Content, Materials, and/or any part of the Service, we shall be entitled to obtain an injunction proscribing such unauthorized use, without the necessity to post bond, and in addition to any other remedies available at law or in equity.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >14. SPECIAL ADMONITIONS FOR INTERNATIONAL USE.</h4>
<p className="text-[18px] text-[#000000]" >14.1 Unless otherwise specified, the Site, the Information, Content, Materials and the Service are presented solely for the purpose of promoting your spiritual and educational awareness and understanding, and promoting certain programs, films, and other products and services available in certain countries. Our Organization has its international headquarters in Orlando, Florida, USA. If you access any of our Sites from outside the United States, be advised that the Site may contain references to Information, Content, Materials, services, products and other information and materials that may not be available, or may be prohibited, in your country. We reserve the right to limit the provision of any of our Site, any Content, any Information, any Materials, and any part of the Service to any person, geographic area or jurisdiction we so chose in the exercise of our sole discretion. The Service, or any part thereof, is void where prohibited.</p>
<p className="text-[18px] text-[#000000]" >14.2 You agree to comply with all local rules regarding the use of our Site (including any Forum), any Information, any Content, any Materials, and any part of the Service, including any local rules regarding acceptable online conduct. You also specifically agree to comply with all applicable laws regarding the transmission of technical data or other information exported from the United States or the country in which you reside.</p>
<p className="text-[18px] text-[#000000]" >14.3 The Software used in association with the Site and the Service may be further subject to United States export controls. No Software may be downloaded, or otherwise exported or re-exported (a) into (or to a national or resident of) Cuba, Libya, North Korea, Iran, Syria, or any other country to which the U.S. has embargoed goods; or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Commerce Department’s Table of Deny Orders. By accessing, downloading or using the Software, or any other materials relating to the Site that are subject to United States export controls, you represent and warrant to us that you are not located in, or a resident or national of, any of the countries identified in subsection (a) of this Paragraph 15.3, and that you are not acting on behalf of, or under the control of a national or resident of any such country, or any person described in subsection (b) of this Paragraph 15.3.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >15.NOTICE AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT INFRINGEMENT.</h4>
<p className="text-[18px] text-[#000000]" >We are committed to respecting the intellectual property rights of other parties, and we ask you, and the other users of our Site and the Service, to do the same. Pursuant to Title 17, United States Code, Sections 512(c)(2) and (3), notifications of claimed copyright infringement for materials displayed, or available, on any of the Site should be sent to our Organization’s Designated Agent. Our Organization’s Designated Agent is:<br /> Dennis R. Kasper, Esq.<br /> Lewis, Brisbois, Bisgaard &amp; Smith, LLP<br /> 221 Figueroa Street, Suite 1200<br /> Los Angeles, CA 90012<br /> 213-250-1800<br /> 213-250-7900 Fax</p>
<h4 className="text-[18px] text-[#000000] font-bold" >16. TERMINATION.</h4>
<p className="text-[18px] text-[#000000]" >These Terms of Use, as may be modified from time to time by us without notice, are effective until we provide notice of termination thereof on our Site. You agree to be bound by the Terms of Use as displayed on each of our Sites at the time you use such Sites and/or any part of the Service provided in connection therewith. You may not terminate any provision of these Terms of Use. Your sole and exclusive remedy is to discontinue your access and use of all our Sites and the Service, and to destroy all Materials and other items obtained from any and all our Site, whether pursuant to the License, or otherwise, together with all related documentation and all copies and installations thereof, except for purchased products. We may terminate your access to any and all our Sites, and/or any part of the Service, at any time in our sole discretion, and we reserve the right at any time to discontinue the operation of any of our Sites, and/or the provision of any part of the Service. We may immediately terminate your right to access and/or use any of our Site and/or the Service, without notice, if, in our sole discretion, you fail to comply with any provision of these Terms of Use.</p>
<h4 className="text-[18px] text-[#000000] font-bold" >17. GENERAL PROVISIONS.</h4>
<p className="text-[18px] text-[#000000]" >17.1 You acknowledge and agree that the unauthorized use of our Site, Information, Content, Materials, and/or any part of the Service could cause irreparable harm to us and/or organizations or individuals that may be associated with us worldwide. Accordingly, you agree that that in the event of any unauthorized use of our Site, any Information, Content, Materials, and/or any part of the Service, we shall be entitled to obtain an injunction proscribing such unauthorized use, without the necessity to post bond, and in addition to any other remedies available at law or in equity.</p>
<p className="text-[18px] text-[#000000]" >17.2 We may at times send you information by e-mail that we believe will be of interest to you. If you register at any of our Sites, and you do not want to receive e-mails from us, please let us know by responding to the unsubscribe action in the message received or contacting us through information on the website.</p>
<p className="text-[18px] text-[#000000]" >17.3 These Terms of Use shall be governed by, and construed in accordance with, the laws of the State of Florida, without giving any effect to any principles of conflicts of law. You agree that any action at law or in equity, and/or any claim arising out of or relating to these Terms of Use, our Site, the Service, and/or your access, and/or use, of any of our Site or the Service, shall be filed and litigated only in the state or federal courts located in Orange County, Florida. You hereby consent and submit to the exclusive personal jurisdiction of such courts for the purposes of litigating any such action or claim.</p>
<p className="text-[18px] text-[#000000]" >17.4 These Terms of Use, as may be amended by us from time to time, constitute our entire agreement with respect to your use of any of our the Site and the Service. These Terms of Use supersede all prior agreements, understandings and representations between us with respect to your use of the Site and the Service. You cannot amend or alter the terms of these Terms of Use.</p>
<p className="text-[18px] text-[#000000]" >17.5 These Terms of Use, including the License, are personal to you, and neither can be assigned by you. You agree not to allow any other person to access and/or use any of the Site or the Service unless such other person agrees to be bound all of the provisions of these Terms of Use. You further agree to assume all responsibility and liability arising from any third party access to, or use of, any of the Site and/or the Service (a) using, or under, any of Your Accounts, or any of your Passwords; and (b) that you permit, knowing that such third party has not agreed to be bound by all of the provisions of these Terms of Use.</p>
<p className="text-[18px] text-[#000000]" >17.6 We may at times send you information by e-mail that we believe will be of interest to you. If you register at any of the Sites, and you do not want to receive e-mails from us, please let us know by responding to the unsubscribe in the message received.</p>
<p className="text-[18px] text-[#000000]" >17.7 If any provision of these Terms of Use is finally found by a court of competent jurisdiction to be void, invalid, unenforceable or otherwise contrary to law or equity, the remaining provisions of these Terms of Use that can be given effect without such void or unenforceable term or provision, shall be given full effect and binding on the parties.</p>
<p className="text-[18px] text-[#000000]" >17.8 Our failure to enforce strict performance of any provision of these Terms of Use, or to penalize any violation by of these Terms of Use, or to penalize you for any further violations of any provision of these Terms of Use.</p>
<p className="text-[18px] text-[#000000]" >17.9 All of the provisions of these Terms of Use, which by their nature, survive the termination of these Terms of Use, shall so survive, including without limitation, the provisions of Paragraphs 3, 4, 5, 6, 8, 9, 10 and 11.</p></div>
			</div>

        </div>
      </section>
    );
  };
  
  export default TermsOfUse;